services:
  gateway:
    volumes:
      - ./gateway/src:/app/src
    command: npm run dev

  auth-service:
    volumes:
      - ./services/auth-service/src:/app/src
    command: npm run dev

  quiz-service:
    volumes:
      - ./services/quiz-service/src:/app/src
    command: npm run dev

  result-service:
    volumes:
      - ./services/result-service/src:/app/src
    command: npm run dev
  frontend:
      build: 
        context: ./frontend
        dockerfile: Dockerfile.dev
      ports:
        - "5173:5173"
      volumes:
        - ./frontend:/app
        - /app/node_modules
      command: ["npm", "run", "dev", "--", "--host"]
      networks:
        - quiz-net
      env_file:
        - ./frontend/.env